### PR TITLE
DESCQA Test for HackUrDC2

### PR DESCRIPTION
**Pull request by dkorytov**
This is a simple DESCQA test that plots the population density of galaxies by redshift and color. This test verifies that the redshift interpolation of galaxy properties from the snapshots galaxy library (Galacticus) is
done a smooth manner and very readily displays any color discreteness in redshift space. I've been using this test in production of cosmoDC2 for a while and I've been wanting to implement in the DESCQA framework so other people can see the results more easily, apply the test themselves and, for myself, to have an easier time managing/sharing the plots.

The branch can be found here: https://github.com/dkorytov/descqa/tree/u/dkorytov/color_z_tests

### CODE REVIEW

**Comment by yymao** [comment]
This is nice @dkorytov! I guess I can look forward to your PR in [DESCQA](https://github.com/LSSTDESC/descqa) as well? :slightly_smiling_face:

**Comment by dkorytov** [comment]
Thanks! Yeah, I'll be doing a PR soon. :)

**Comment by rmandelb** [comment]
@dkorytov - we are looking to merge the HackurDC2-related PRs in the coming days.  Might you be  available to address the review comments by ~early next week?  Hopefully they can be done with quite minor modifications.

**Comment by dkorytov** [comment]
@rmandelb, Sure, I'll knock it out.

**Comment by dkorytov** [comment]
@evevkovacs, the plotting routine already displays any cuts applied inside the plot: https://github.com/LSSTDESC/DC2-analysis/blob/fa1931c3b1550686131623f87a311cd038ad5bfe/contributed/plots/dkorytov/fig3.png

@yymao, I've updated the readme.

**Comment by rmandelb** [comment]
Since the reviews were addressed, I'm going to go ahead and merge this.  Thanks @dkorytov !

**Pull request merged**
