### PR TITLE
Update star truth catalog in `matching_fof` tutorial

### LINKED ISSUE #160: old truth file referenced in tutorial notebook
@nipauna ran into the problem that in https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/matching_fof.ipynb there is a reference to `/global/cfs/projectdirs/lsst/groups/SSim/DC2/all_stars_DC2_run2.1i.fits.gz` instead of the new truth catalog

### PR DESCRIPTION
**Pull request by yymao**
This PR fixes #160. 

I updated the star truth catalog to use what's available in `GCRCatalogs`. Also made some minor changes to the tutorials for things that are outdated, and to make some code a bit more readable.

### CODE REVIEW

**Review by johannct — COMMENTED** [review]
LGTM. I'll clear it though I have two proposals that I leave to you to decide to implement or not

**Review by johannct — APPROVED** [review]
forgot to clear the way to merging. My two comments are not strictly required

**Comment by yymao** [comment]
@johannct Thanks. I've addressed your comments.  For the second question, the lensing effect is really small to eye, so it's true that we won't *see* clear difference on the scatter plot.  I have hence added a note about this in the notebook.

**Comment by nipauna** [comment]
@yymao and @johannct thank you very much! 
Nicoleta

**Pull request merged**
