### PR TITLE
Galaxy Clusters & Velocity: A HackUrDC2 Story

### PR DESCRIPTION
**Pull request by JulienPeloton**
**Context**

This notebook is part of the HackUrDC2. Its purpose is to illustrate the basics of accessing the cosmoDC2 catalog through Apache Spark as well as how to select useful samples of data to study galaxy clusters & their velocity. 

**Science results or validation?**

While it describes some of the science results you can get with the DC2 catalog (e.g. halo mass-velocity dispersion relation), it shifted towards the validation side, especially on the halo mass distribution. So it is a bit of both! After going through this notebook, you should be able to:

- Load and efficiently access the cosmoDC2 catalog with Apache Spark
- Apply cuts to the catalog using Spark SQL functionalities
- Have several example of quality cuts and validation procedures 
- Derive scientific results on galaxy clusters
- Distribute the computation and the plotting routine to be faster!

**Table of contents:**
- Loading cosmoDC2 data with Apache Spark
- Halo mass distribution
  - issue: https://github.com/LSSTDESC/DC2-analysis/issues/55
- Galaxy clusters and velocity
  - A few individual galaxy clusters
  - A wider region of space
  - Mean velocity as a function of redshift
- The velocity dispersion–halo mass relation
  - issue: https://github.com/LSSTDESC/DC2-analysis/issues/57
- Visualising masses in the cosmoDC2 Universe
- Outro: Towards large data sets with Apache Spark

**Thanks to:**

[@aphearin](https://github.com/aphearin), [@cwwalter](https://github.com/cwwalter), [@dkorytov](https://github.com/dkorytov), [@rmandelb](https://github.com/rmandelb), [@salmanhabib](https://github.com/salmanhabib), [@yymao](https://github.com/yymao), for their help in understanding better how DC2 catalog was made, and solving issues while making this notebook!

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Thanks @EiffL for the review! 

- Section `Halo mass distribution in DC2`: Right - I added few more lines, and an image describing the data flow. I hope this helps!
- Section `Mean velocity as a function of redshift`: I added this section at the last minute, noticing that some additional information could be extracted from this. But since I'm not an expert, I struggled making a useful comment on it... So I agree it lacks of investigation (or description) to be fully part of the notebook. I will wait for @katrinheitmann for hints on the relevance of this plot here, skipping it otherwise.
- Section `The velocity dispersion–halo mass relation`: Good catch! Done.

**Comment by rmandelb** [comment]
@EiffL - might you be able to check in the coming few days whether @JulienPeloton 's commits resolved your review comments adequately? We would like to start merging these PRs in the coming few days.

Thanks!

**Comment by EiffL** [comment]
Thanks @JulienPeloton , this is a great notebook and easily  meets the standard of quality for this repo. Thanks for your patience with my slow response  time :-/

**Comment by JulienPeloton** [comment]
Thanks @EiffL for your time and your reviewing work!

**Comment by rmandelb** [comment]
Great- I think we are nearly ready to merge, but we have been asking people to clear the notebook outputs before merging to master (following the instructions [here](https://github.com/LSSTDESC/DC2-analysis/tree/master/contributed)).  @JulienPeloton can you please do that, and then we can merge?

**Comment by JulienPeloton** [comment]
Thanks @rmandelb, all notebook outputs cleared!

**Comment by rmandelb** [comment]
Thanks @JulienPeloton - I am going to merge now!

**Pull request merged**
