### PR TITLE
U/lal/hackurdc2 the movie

### PR DESCRIPTION
**Pull request by plaszczy**
The following represent a LAL team contribution to the HackUrDC2 challenge

- Our preliminary work was to provide to DESC collaborators some simplified ways to use Spark at NERSC: [desc-spark](https://github.com/LSSTDESC/desc-spark). This culminated with the `desc-pyspark` kernel we built/installed for jupyter users. Note that jupyter-dev is currently limited to 4 threads/users and does not pay tribute (yet) to the full Spark power. Once more data will be available this will become more and more clear...

- as an illustration, we wanted to have a look at DC2 3D catalogs since we believe that the eye is a powerful tool to reveal issues but also because it looks so nice and want to train people using Spark. To this purpose we first needed to export the data to a format easily readable by Spark and we choose the "parquet" one. The script for exporting some relevant quantities can be found [here](https://github.com/LSSTDESC/DC2-production/blob/issues/273/scripts/prod/cori/CosmoDC2/cosmoDC2_to_parquet.py).

- thanks to the `desc-pyspark` kernel, we can then have a 3D look at the latest extragalactic CosmoDC2 catalog: the following notebook shows how, and can be view as the "making of" our great CosmoDC2 movie.
  
- Finally we did import the data to our [local cluster](https://www.informatique-scientifique.u-psud.fr/services/spark.html) and used some sophisticated visualization tools (https://gbarrand.github.io) that we plugged into Spark. We plan to make these tools available to the Collaboration in the next year.

The final movie we made to illustrate the display of the catalog is at the end of the
Notebook (see also https://www.youtube.com/watch?v=HC_CQA5cOag) : it
tries to capture the overall "feeling" but we are (clearly) not filmakers. We
also provide a high resolution picture that can be incorporated more
easily within a presentation.

Stephane for the
Spark/LAL team (C. Arnault, G. Barrand, J.E Campagne, J. Peloton, S. Plaszczynski)

On the Spark training side, we also produced the following notebooks that may help people start with:

**Accessing the data**
- [object_spark_1_intro](https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/object_spark_1_intro.ipynb)
- [object_catalog_performance_spark](https://github.com/LSSTDESC/DC2-production/blob/master/Notebooks/object_catalog_performance_spark.ipynb)

**Playing with the data**
- [footprint_Run12p_spark](https://github.com/LSSTDESC/DC2-production/blob/u/plaszczy/nb_run1_2/Notebooks/footprint_Run12p_spark.ipynb)
- [Colors_Run12p_spark](https://github.com/LSSTDESC/DC2-production/blob/u/plaszczy/nb_run1_2/Notebooks/Colors_Run12p_spark.ipynb)
- [Number_density_Run1.2](https://github.com/LSSTDESC/DC2-production/blob/u/plaszczy/nb_run1_2/Notebooks/Number_density_Run1.2.ipynb)
- [hackurdc2_spark_halos](https://github.com/LSSTDESC/DC2-analysis/blob/u/JulienPeloton/hackurdc2_spark_halos/contributed/hackurdc2_spark_halos.ipynb)

gb2

### CODE REVIEW

**Comment by rmandelb** [comment]
@plaszczy @JulienPeloton - we are looking to merge the HackurDC2-related PRs in the coming days. Might you be available to address the review comments from Jim by ~early next week? Hopefully they can be done with quite minor modifications. 

Thanks!

**Comment by plaszczy** [comment]
@rmandelb we are finishing a paper by tomororow. early next week should be ok.

**Comment by rmandelb** [comment]
Great, thank you!

**Comment by plaszczy** [comment]
Hi @jchiang87 @reneehlozek 
thanks for the review, should be clearer for newcommers now
- add some intrcduction about spark to put in perspective + usefull docs (as on sql functions)
- we actually  wrote another notebook for our paper, so added ref to it
-comment ton the imes observed
-add your comparison with hist: good idea to make feel what distributed computing is

best

**Comment by jchiang87** [comment]
Hi @plaszczy,

Thanks a lot for the changes and for providing this helpful illustration of using these tools.  Everything looks good to me.

**Comment by rmandelb** [comment]
Thanks @jchiang87 !  

One thing I just noticed, which I previously overlooked: this notebook is in tutorials/, not contributed/.  For tutorials/ we have some additional requests to make sure the tutorials are pedagogically useful (the tasks for submitting tutorials are outlined in [this README](https://github.com/LSSTDESC/DC2-analysis/tree/u/LAL/hackurdc2_TheMovie/tutorials#notes-for-tutorial-contributors) - e.g., the tutorials need to be added to the master list, and there should be some learning objectives outlined at the top).  We've also generally held them to a different review standard.  So @plaszczy , I think there are two ways forward:

1. You can move the notebook to contributed/, clear the outputs (which we are doing for all notebooks before merging to master, whether they are in contributed/ or tutorials/), and then we merge.
2. You can do the additional steps to keep this in tutorials/, clear the outputs, and then we merge.

What's your preference?  It is your choice.  And it's a very useful notebook regardless of where it lives.

**Comment by plaszczy** [comment]
we already have some notebook about spark in tutorials. Probably it would worth updating the header with this one (and add a link to it). I moved this one  to contributed.

**Comment by rmandelb** [comment]
Great!  Once you clear the notebook outputs, we can merge.  :)  Thanks!

**Comment by plaszczy** [comment]
OK done

**Pull request merged**
