### PR TITLE
Flesh out README in top directory of repo

### PR DESCRIPTION
**Pull request by rmandelb**
This PR addresses part of issue #1 by fleshing out the README in the top directory of this repository.  It's still fairly basic but probably sufficient given that it can link to the subdirectory READMEs for more info.

In #3 we were discussing a `contributed` directory that will have a README Yao is putting together about how to contribute material, but the directory doesn't exist yet, so right now there is a note that linking to that directory and its README is TBD.

### CODE REVIEW

**Comment by yymao** [comment]
I think we can add a link to `contributed/README.md`?

**Comment by wmwv** [comment]
Yes, once `issue/3/add-contributing-instructions` is merged.
(But, really, the order doesn't matter; these will all be merged in the next day or so.)

**Comment by rmandelb** [comment]
@yymao @wmwv - I added it in https://github.com/LSSTDESC/DC2-analysis/pull/8/commits/3fd1c88abf7d99cb36b2f15fd23485ad95500ce5 so I think this one should be good to go.  We can merge them together when the other PR is ready.

**Comment by rmandelb** [comment]
@yymao - I just noticed Phil commented on this 30 minutes ago (I missed it) so I'm not merging this one.  It's OK, we can deal with it later, and just mention on the telecon that the repo is still being put together...

**Comment by rmandelb** [comment]
@drphilmarshall - thanks!  Yao is ahead of you, he already included the 3-clause license from DC2-production here too.  :) I've added a section of the README per your suggestion in https://github.com/LSSTDESC/DC2-analysis/pull/8/commits/8934d488f1c4babb6f7e8aa45be7818f7e1b654d.  Perhaps @yymao could check that out and see whether the statements about indicating the state of the code is consistent with our instructions to contributors as well?

Regarding your proposed way of acknowledging use of the notebooks, 'An acknowledgment to the notebook's owner(s) and a link to this repo' sounds appropriate to me, but it would be good to wait a little before merging so some more notebook owners have a chance to see this and comment.

**Comment by yymao** [comment]
@rmandelb The statements about the state of the code looks good to me. 

As for acknowledging the use of the notebooks, I think the statement you added is fine, but agree that we should loop in other tutorial writers. Instead of waiting for them to discover this PR, I am just going to be an annoying person and @ them all here: @wmwv @EiffL @fjaviersanchez @dkorytov @evevkovacs @jchiang87 @danielsf

**Comment by evevkovacs** [comment]
Fine with me

**Comment by danielsf** [comment]
LGTM

**Comment by rmandelb** [comment]
All review comments have now been addressed.  We've gotten explicit approval for the lightweight acknowledgment method from 3 tutorial developers (two here, one offline) and others who are definitely watching this repo did not object, so I think we are good to go.  I would like to merge this now so the master branch of the repo has a functional top-level README, but of course further issues can be opened for additional cleanup.

**Pull request merged**
