### PR TITLE
Added validation notebooks for 1.2i/p

### PR DESCRIPTION
**Pull request by fjaviersanchez**
I opened a fresh PR to better track the addition of some notebooks that I used for validation purposes. Comments and suggestions are welcome.

### CODE REVIEW

**Comment by yymao** [comment]
@fjaviersanchez sorry for the delay; I just started to look at these notebooks. I notice there's quite some code repetition on extracting the columns in `src_cat` into local scope, and I wonder if we can streamline those by using GCR. For example:

```python
from collections import defaultdict
from GCR import BaseGenericCatalog

class QuickSrcCatalog(BaseGenericCatalog):
    def _subclass_init(src_cat, calib):
        self._src_cat = src_cat
        self._quantity_modifiers = {
            'nchild_imsim': 'deblend_nChild',
            'ra_imsim': (np.degrees, 'coord_ra'),
            'dec_imsim': (np.degrees, 'coord_dec'),
            'mag_k_imsim': (calib.getMagnitude, 'ext_photometryKron_KronFlux_instFlux'),
            'x_im', 'base_SdssCentroid_x',
			# add more here ...
        }
        
    def _generate_native_quantity_list(self):
        return self._src_cat.schema.getNames()
        
    def _iter_native_dataset(self, native_filters=None):
        yield self._src_cat.get

data = defaultdict(list)
for i, visitId in enumerate(datarefs.cache):
	# here's other preparation code in the for loop 
	src_cat_reader = QuickSrcCatalog(src_cat, calib)
	for q in src_cat_reader.list_all_quantities():
		data[q].append(src_cat_reader[q])

for k, v in data.items():
	data[k] = np.hstack(v).ravel()
```

If it's overkill to use GCR, you can ignore that part. You should make use of `defaultdict` still, as it can still save many lines of defining empty lists and concatenate arrays.

In the end, if you do want to expose all these arrays into the local scope, you can simply do:
```python
locals().update(data)
```

I'll continue to review other parts of the notebooks.

**Comment by rmandelb** [comment]
@fjaviersanchez - I was wondering what's the status of this PR?  Do you anticipate continuing to  update the notebooks (e.g. in response to Yao's comment), or should we try to get a more full review going?  It's been dormant for  a while so I wanted to check in.

**Comment by fjaviersanchez** [comment]
I am so sorry, I forgot about this. I'll update them in the next few days (there are now parts in GCRCatalogs that address some of Yao's comments).

**Comment by reneehlozek** [comment]
hi @fjaviersanchez, just wanted to check on the status of this PR?

**Comment by fjaviersanchez** [comment]
@reneehlozek, thanks for following up. I re-started working on this a few days ago and hope to have something finished by the end of the week.

**Comment by fjaviersanchez** [comment]
@yymao Apologies for the really long delay. I updated the notebooks and simplified them as requested. The notebooks are still pending getting the latest version of `GCRCatalogs` in the `desc-stack` kernel. Once that's done please feel free to review or to assign a different reviewer. Thanks a bunch in advance!

**Comment by yymao** [comment]
@fjaviersanchez thanks for the update. This looks good. I have some rather minor coding style suggestions for you to consider. None of these affect the functionality of the notebook; they are merely small style differences/preferences. 


### In `DC2_calexp_src_validation_1p2.ipynb`

#### Cells 12 and 13
Use `add_derived_quantities` to homogenize column names, so that one can use the same `get_quantities` statements on both catalogs.
```python
gc.add_derived_quantities('ra', np.degrees, 'coord_ra')
gc.add_derived_quantities('dec', np.degrees, 'coord_dec')
gc.add_derived_quantities('star', np.logical_not, 'is_resolved')
for band in 'ugrizy':
    gc.add_derived_quantities('mag_true_%s'%band, lambda x: x, 'mag_%s_lsst'%band)
```

#### Cell 142
- If `ra` and `dec` is added by `add_derived_quantities` and loaded by `get_quantities`, then one can just do: 
```python
plt.scatter(data_im['ra'][::10], data_im['dec'][::10], s=0.01)
```

#### Cell 98
Most healpy functions have the `lonlat` option, which when set to `True`, the function takes RA and Dec in degrees directly, making the code cleaner. 
```python
pixnums = hp.ang2pix(4096, data_im['ra'], data_im['dec'], lonlat=True)
pixnums_true = hp.ang2pix(4096, data['ra']), data['dec'], lonlat=True)
```
(similarly in cell 126)

#### Cell 104
```python
mask_mag = (~np.isnan(mag_psf)) & (matched) & (data['star'][in_footprint][ind_mag])
```
OR
```python
mask_mag = (np.isfinite(mag_psf)) & (matched) & (data['star'][in_footprint][ind_mag])
```

### In `Run_1.2p_PSF_tests.ipynb`

#### Function `get_visits`
- Use `?` in `execute` because it's a good practice to avoid SQL injection attack
- Move the code that turns the returned list into numpy array into this function, as it's rather a technical detail.  
```python
def get_visits(conn,min_alt=80, min_seeing=0.60, max_seeing=0.8):
    cur = conn.cursor()
    cur.execute("SELECT obsHistID, filter FROM ObsHistory WHERE altitude > ? and finSeeing > ? and finSeeing < ? and filter='r'", np.radians(min_alt), min_seeing, max_seeing)
    return np.array(cur.fetchall()).ravel().astype(np.int)
```

#### `for visitId in datarefs.cache` loop
- This loop seems unnecessary because the `in1d` statement right after it. We can simplify those cells: 
```python
good_visits = get_visits(conn)
all_visits = np.fromiter((visitId['visit'] for visitId in datarefs.cache), np.int)
visits_to_check = all_visits[np.in1d(all_visits, good_visits)]
print(len(good_visits), len(all_visits), len(visits_to_check))
```

#### The loop that collects data
- Move `concatenate` outside the loop and do simple list `append` within the loop to (i) avoid if statement and (ii) save time (concatenate is more expensive than append)
- Utilize GCR's native feature `add_derived_quantity`
- Instead of slicing `visits_to_check`, put an if statement at the end of the loop to break. This makes the code more modularized and readable.  
```python
nvisits_to_query = 3 # We are going to check 3 visits only but feel free to query up to 22!

data = []
for i, visit_this in enumerate(visits_to_check):
    cat = SingleVisitCatalog(repo=data_imsim, filter_band='r', visit=visit_this, detector=None)
    cat.add_derived_quantity('e_psf_i', get_e, 'base_SdssShape_psf_xx', 'base_SdssShape_psf_yy', 'base_SdssShape_psf_xy')
    data_this = cat.get_quantities([columns + 'e_psf_i'], filters=['deblend_nChild == 0'])
    data.append(data_this)
    if i >= nvisits_to_query:
        break
    
data = {q: np.concatenate([data_this[q] for data_this in data]) for q in data[0]}
```

**Comment by fjaviersanchez** [comment]
@yymao Thanks a lot for taking a look and for the useful suggestions (I learned some new stuff from them!)

**Comment by reneehlozek** [comment]
This is approved to merge, so unless I hear anything from folks in the next 24 hours I'm going to merge - please shout @rmjarvis if that's not ok!

**Pull request merged**
