### PR TITLE
Add SED_PCA notebook contribution for HackUrDC2

### PR DESCRIPTION
**Pull request by evevkovacs**
Here's a notebook contributed by Eve Kovacs and Andrew Hearin to perform a PCA decomposition of central red-sequence galaxies in cosmoDC2

### CODE REVIEW

**Comment by fjaviersanchez** [comment]
@evevkovacs Thanks a lot for the contribution. I think that, overall it is a good example of how to load and analyze some of the data and it is great work! It has some interesting analysis techniques (PCA). I was able to run your notebook on NERSC and I have some comments:

1) If I used it as it is right now, since I don't have permissions to your NERSC home, I wouldn't be able to load the catalog. I would suggest to take out this: `sys.path.insert(0, '/global/u1/k/kovacs/gcr-catalogs_cosmoDC2_v1.1')` in cell 2 and change this in cell 4 `catalogs = ['cosmoDC2_v1.1.4_9556']`  to this `catalogs = ['cosmoDC2_v1.1.4_image']`. And then in cell 5, when you query the data here: `catdata[catalog] = gc.get_quantities(quantities)` you can change it to `catdata[catalog] = gc.get_quantities(quantities, native_filters='healpix_pixel == 9556')`. This way you only query that healpix pixel. In any case, this is just a suggestion. Another option is to give us permission to read that or add that specific configuration file to `gcr-catalogs`.

2) There are some typos , e.g., `which is expected since we colors would characterize changes in shape from 0th eigenvector.`

3) I think that the notebook would benefit from some further discussion about the results (there is some discussion on the 0th component but maybe it would be good to elaborate a bit more).

**Comment by danielsf** [comment]
You should probably also add a docstring to the `analyze_SEDs` method, at least defining what is returned.  At first glance, it looks like the method just exists to generate plots, though a careful reading shows that it also returns dicts of eigenvectors and values.

**Comment by danielsf** [comment]
I wonder if there should be symbols at the actual data points on the plots produced by `analyze_SEDs`, so that users don't get the impression that you are plotting continuous SEDs.

**Comment by evevkovacs** [comment]
Thanks very much for the comments. I made changes to the notebook to address them. I hope I caught all the typos in descriptions

**Comment by rmandelb** [comment]
@danielsf @fjaviersanchez - we are hoping to start merging in these HackurDC2 PRs in the coming few days.  Might you be able to quickly check in the coming few days whether Eve's changes satisfy your review comments, so you can approve the PR for merging?

Thanks!

**Comment by fjaviersanchez** [comment]
The changes look good to me! If @danielsf agrees please go ahead and merge.

**Comment by rmandelb** [comment]
Based on my own look at this, I would like to go ahead and merge with one reviewer approval. @evevkovacs could you please commit a version with the notebook outputs cleared, and we can go ahead and merge as soon as that's done?

**Comment by evevkovacs** [comment]
@rmandelb  I removed the outputs and pushed the notebook. It should be ready to merge.

**Pull request merged**
