### PR TITLE
Add a notebook to contributed for comparing observational and galaxy properties in DC2

### PR DESCRIPTION
**Pull request by nehapjoshi**
I have added the notebook Observation_vs_galaxy.ipynb under contributed.  This is the notebook that was addressed in issue #112.  It uses data from Run2.1i to test correlations between observational and galaxy properties.

direct link to notebook: https://github.com/LSSTDESC/DC2-analysis/blob/u/npjoshi/validation-notebooks/contributed/Observation_vs_galaxy.ipynb

### CODE REVIEW

**Comment by fjaviersanchez** [comment]
Thanks a lot @nehapjoshi! The notebook looks good and I managed to run everything. We have to think about what the blendedness plots mean because they are difficult to interpret (at least to me). Also, it would be cool to see something similar to this for stars but maybe it's fine to do that in a different notebook.

**Comment by fjaviersanchez** [comment]
I'll leave this open until tomorrow and will merge then if nobody else has comments.

Also, @nehapjoshi, @rmandelb; @zdu863 has prepared some maps of observational quantities (mean seeing, mean skybrightness, mean sky noise, etc) for Run 1.2i. Would you be interested in doing similar tests using those maps in a different notebook? 

@zdu863, would you be willing to share your maps via `gcr-catalogs`? I can help with this if @yymao and @wmwv agree to have them as part of `GCRCatalogs`.

@yymao and @wmwv would it be ok to have these maps available in `GCRCatalogs`? They are in [healsparse](https://github.com/LSSTDESC/healsparse) format so that would increase the dependency tree. I don't think that these maps need much disk space nor long-term support/updates since they can also be stored in standard healpix format and are "static" files for Runs 1.2i/p.

Also @zdu863, would you be willing to prepare similar maps for run 2.1i? (it's a larger data volume than run 1.2i so it may be a useful exercise for you if you wanted to parallelize the map generation, please feel free to say no if you don't have time).

**Comment by yymao** [comment]
Sure, should be straight forward to include in GCRCatalogs I think.

**Comment by zdu863** [comment]
Sure, I can share the maps on `gcr-catalogs`, but I'm not sure how, I'll need your help on that.

I'm willing to prepare the maps for run 2.1 too.

**Comment by fjaviersanchez** [comment]
Perfect, since nobody has complained, I'll go ahead and merge and open a new issue to track down the validation using Zilong's maps! Thanks to all!

**Pull request merged**
