### PR TITLE
U/chihway/gglensing stellarmass

### PR DESCRIPTION
**Pull request by chihway**
In this notebook we show the galaxy-galaxy lensing signal ($\Delta \Sigma$) measured from CosmoDC2 where we attempt to match the lens selection to those used in Mandelbaum et al. (2016; M16; 1509.06762). This analysis tests the extent of the simulations that we can trust in terms of:

- scales useful for lensing measurements
- galaxy-halo connection as a function of stellar mass and colors

Contributors to this test and relevant discussion include:
Chihway Chang, Andrew Hearin, Patricia Larsen

### CODE REVIEW

**Comment by sethdigel** [comment]
Here are some comments for your consideration on the TestGalaxyGalaxyLensingSDSSMain.ipynb notebook.

I used the cosmoDC2_image catalog, which... -> [Here it would be useful to the neophyte to show how you extracted these counts from the cosmoDC2_image catalog]

Next we plot the $\Delta \Sigma$ measurements -> [Not including the measurement code makes sense, but it would be worth adding some details about what (else) you needed to extract from the cosmoDC2_image catalog to feed to treecorr, and how you extracted it.]

Below 20-30 Mpc/h, the simulations show surpressed signal -> [I'm not sure that i see this in the plots.  Do you mean 0.02-0.03 Mpc/h?  Or maybe add some more words for the easily confused.]

**Typos:**
tests the extent of the simulations that we can trust  -> tests the extent to which we can trust the simulations
sclaes  -> scales
lens selection are -> lens selections are
number of lens galaxies -> number of lensed galaxies [?]
blud galaxies -> blue galaxies
surpressed signal -> supressed signal
number dnesity -> number density

**Comment by chihway** [comment]
Thanks for the feedback, @sethdigel , and apologies for the embarrassing typos... I believe I have addressed your comments, but let me know if there's anything else I could add to make the notebook clearer.

**Comment by rmandelb** [comment]
@sethdigel - might you have a chance in the coming few days to check out whether Chihway's updates satisfactorily address your comments, and if so, leave a review approving this PR?  We'd like to start merging these HackurDC2 PRs soon.

Thanks!

**Comment by rmandelb** [comment]
Great, thanks!   @chihway , the last step before we merge is to clear the notebook output following the instructions in [this readme](https://github.com/LSSTDESC/DC2-analysis/tree/master/contributed).  And then we are all set....

**Comment by chihway** [comment]
Ok, @rmandelb, I think I just did, let me know if there's further questions.

**Comment by rmandelb** [comment]
Great, thanks @chihway !  I'll merge this now.

**Pull request merged**
