### PR TITLE
Submit redMaPPer catalogs for HackUrDC2

### PR DESCRIPTION
**Pull request by erykoff**

### CODE REVIEW

**Comment by erykoff** [comment]
The code that actually runs redMaPPer has multiple steps, requires a bunch of memory, and should be run on a cluster, so is not really suitable for a notebook.  I'm working on the documentation and can add better demonstrations of how to run on cosmoDC2 in the near future, but that's outside the scope of my hackurdc2 submission, which I focused on the use of the catalog now that it's available.

I'll add more documentation to the descriptions of the plots.

Finally, galaxy photometric redshifts are hard, but red galaxies are easier, and clusters you can do incredibly well by fitting all the red galaxies simultaneously.  Though sigma_z/(1+z) ~ 0.005 is actually achievable in data (though not at all redshifts), we're really helped here by the complete lack of observational systematics.  I'll add a note about this.

**Comment by rmandelb** [comment]
@danielsf - we are hoping to start merging in these HackurDC2 PRs in the coming few days. Might you be able to quickly check in the coming few days whether Eli's changes satisfy your review comments, so you can approve the PR for merging?

Thanks!

**Comment by rmandelb** [comment]
Based on my look at the updates, I would like to go ahead and merge this.   @erykoff can you please clear the notebook outputs, and then we'll go ahead?

**Comment by yymao** [comment]
@erykoff @rmandelb I took the liberty of clearing the notebook output. Since @danielsf has approved, I am merging this now.

**Pull request merged**
