### PR TITLE
Add plots from Piff running on DC2 1.2i

### PR DESCRIPTION
**Pull request by rmjarvis**
I'm submitting some plots made by Piff running on DC2 1.2i field 00261962-i.  These include:

1. Rho statistics (rho.png).  The most notable is rho_1, which is the auto-correlation of the residual shapes between the model and the data.  This is one of the key metrics of PSF fidelity for weak lensing studies.  The results look quite good, as do the other 4 rhos stats, which involve different auto- and cross-correlations that are relevant to shear measurement errors.
2. Spatial distribution of size and shape errors (twod.png).  These used to show significant outliers that were too numerous for Piff to do a good job of removing them.  But switching to the DM PSF stars for the input list works well, and there don't seem to be any big outliers present.
3. Histogram of the size and shape measurements and residuals (shape.png).  These probably aren't so informative, but it is the other statistic we have currently built into Piff.  They seem to match up fairly well, and the residuals are pretty well centered at zero, so that's good.

The Piff configuration file I used is also submitted in the same directory (`contributed/plots/piff_dc2`).  This was run at nersc using the command `piffify piff_single_1.2i.yaml`.

It turned out that there were a number of changes required to Piff to get it to properly read in the LSST DM data products.  These are in [Piff PR \#79](https://github.com/rmjarvis/Piff/pull/79).

The main change that we may want to push back on DM about is that their variance plane images include the signal as part of the variance.  This is almost never the right thing to use for model fitting. 

Piff expects the variance to just include noise from the sky, read noise, dark current, etc.  But specifically, **not** the signal.  So I had to add code that subtracts off the signal from the variance to get it in the format that Piff is expecting.

@esheldon ran into the same issue, and it will probably keep cropping up.  The easiest long term solution, I think, would be for DM to add another hdu to the calexp files with a normal weight image = 1/variance, where the variance does not include the poisson shot noise from the signal.

### CODE REVIEW

**Comment by RobertLuptonTheGood** [comment]
Mike says: "Piff expects the variance to just include noise from the sky, read noise, dark current, etc. But specifically, not the signal. So I had to add code that subtracts off the signal from the variance to get it in the format that Piff is expecting." and this is of course correct (and we don't use the variance for model fitting).   However, I'm not sure that removing the object noise from the variance is the right thing to do -- for example, for detection you probably *do* want to the object variance, although you would have to worry about biases.
I'm not sure how Mike wants DM to remove the object photon noise; I'd have thought that what he really wanted is to know would be the noise model and the sky level in each pixel.  I'd have to check, but I think that this is all available.  So I think this comes down to an interface to get that noise, rather than adding it to the calexps.

**Comment by rmandelb** [comment]
@rmjarvis - we are looking to merge the HackurDC2-related PRs in the coming days. Might you be available to address the review comments by ~early next week? Hopefully they can be done with quite minor modifications.

Thanks!

**Comment by rmjarvis** [comment]
Yao said:
> For someone like me who has little idea about Piff, I think it would be very useful to...

Done.

> Also, I noticed that piff is not installed in the shared DESC environment. Is this a package that we should install so that members can use it easily without the need to install their own?

Certainly eventually.  And maybe already.  It's a package that is still in fairly active development, so I don't know how averse you are to including unstable packages in that environment.  I don't really use the DESC environment much myself, but then I'm more comfortable installing things myself than most people are.  (And I don't use the DM stack, so that's not something I need to keep up to date for my purposes.)

Perhaps the most appropriate action is to wait until someone requests it?

**Comment by rmjarvis** [comment]
Robert said
> I'm not sure how Mike wants DM to remove the object photon noise; I'd have thought that what he really wanted is to know would be the noise model and the sky level in each pixel. I'd have to check, but I think that this is all available. So I think this comes down to an interface to get that noise, rather than adding it to the calexps.

Well, it's now a solved problem in Piff, so for that purpose, I don't need anything from DM particularly.  The calexps include both the full variance including the signal as well as the signal itself (i.e. the image), so it's relatively straightforward to do that calculation and subtract it off.  

However, I expect that this will be something that keeps coming up as other projects desire to do any kind of model measurement on the images.  Indeed it surprised me that DM didn't already have such a thing calculated for your own model fitting algorithms.  Using the full variance including the variance from the shot noise of the signal leads to biased sizes and shapes.  (Probably not so important for flux I guess.)  The right procedure is to let the model tell you the Poisson variance from the expected signal at each point rather than use the realized number of photons.

So either the solution I implemented in Piff needs to become lore that gets passed around among people who want to use the images directly, or DM can add the more usual kind of weight map (inverse variance without signal) as another hdu.  I think in the long run, the latter option makes more sense, but it is kind of up to you.

**Comment by rmjarvis** [comment]
Jim said
> A link to the ADS entry for your 2016 paper (http://adsabs.harvard.edu/abs/2016MNRAS.460.2245J) would also helpful.  Regarding your plot comments, could you be more quantitative on what would be good numbers for the various rho stats for data like this? As a non-expert, I'm not sure how to interpret, say, the rho_1 points given plots like Figure 10 in the 2016 paper.

Done.  (Mostly at this point, the takeaway is that it is broadly consistent with no signal.  Once we run this on more images and beat down the noise, we'll have a better handle on whether there is any problematic correlations here that we need to work on.)

> Finally (and I realize this is well outside the scope of this PR), would it make sense to compute these statistics and make these plots for the PSF model used by the DM code?
I expect there would need to be some development in the PIFF package or elsewhere get that to work, but seeing comparisons between the performance of the current PSF model in the DM code vs what Piff obtains might be interesting.

It is definitely outside the scope of what I did here, but I'll see about running that measurement when I expand this up to running on all of DC2.

**Comment by rmandelb** [comment]
By all means feel free to keep discussing these other issues (e.g. Piff installation at NERSC), but I am going to go ahead and merge the plots in to master now.

**Pull request merged**
