### PR TITLE
Issues/98 - Improve covered area calculations to use healpix

### PR DESCRIPTION
**Pull request by wmwv**
Improve the area calculation by using healpixels to count area.

I've included a rendered version for convenience of review.

### CODE REVIEW

**Comment by wmwv** [comment]
@bechtol Could you take a quick look at this healpy-based area calculation change?

**Comment by bechtol** [comment]
The `calculate_area` function looks like a good approach to quickly estimate the areal coverage in terms of the number of detected objects. For different datasets, the choices of `nside` and `threshold` parameters might need to be tuned for accuracy, but since these are easily configurable, it seems that users could modify if needed. One could imagine a check that estimates how many pixels would be empty due to Poisson fluctuations. 

When I run the notebook on cori, the notebook spends several minutes (at least 15 minutes) on the cell `cat = GCRCatalogs.load_catalog(catalog_name)` and seems hang, so I haven't been able to directly verify the cells around the `calculate_area` function.

Looks OK to me.

**Comment by wmwv** [comment]
@bechtol 

If you just load the one-tract version of the Run2.1i catalog 
```
catalog_name = 'dc2_object_run2.1i_dr1_tract4850
```

can you run through the cells successfully?

I included the full catalog in the rendered version I checked in so that you can see the effect, but it does take a _long_ time to run.

**Comment by bechtol** [comment]
Sorry I didn't see the `catalog_name = 'dc2_object_run2.1i_dr1_tract4850'` option in the cell above. I can confirm that all the cells run successfully.

There is a problem with the `threshold` argument to the `calculate_area` function in that this argument isn't actually used. Rather, the value of `threshold` is set in the function. I think the intent was something like the following:

```
    # Take only pixels where the counts are greater than a specified 
    # fraction of the median value of the non-zero counts/pixel. 
    # We already know that these are just counts from above.
    threshold_counts = threshold * np.median(counts)
    if verbose:
        print(f'Median {np.median(counts)} objects/pixel')
        print(f'Only count pixels with more than {threshold} objects')
    significant_pixels, = np.where(counts > threshold_counts)
```

**Comment by wmwv** [comment]
> The extendedness section was very informative but I'm now very confused by what it means for mag_psf - mag_cmodel to be zero. Are these objects that are (approx.) equally likely to be stars at an arbitrary distance as they are distant galaxies with lower SNR?

@djperrefort There's no distance statement or apparent magnitude prior.  The SNR of the object is certainly the same.  This is just about the relative shape (i.e. the distribution of flux across the pixels).  So if the magnitude assuming a PSF is the same as fitting the best-fit extended model, then that really means that the best-fit extended model is the PSF and thus there's no information in the shape that allows us to distinguish the object from being a star.

FWIW, while I did indeed direct a review of this to you for your general edification and am always happy to share knowledge and perpetuate learning :),  this PR is only on the changed parts about calculating area.

**Comment by wmwv** [comment]
Thanks for the reviews, @bechtol and @djperrefort .  Would one of you be kind enough to formally Approve this PR?

**Pull request merged**
