### PR TITLE
Issues/67 - Add Inspection Notebook for DC2 Object Tables

### PR DESCRIPTION
**Pull request by wmwv**
This presents a visualization of some basic things for a DPDD-formatted Object Table catalog.

What calculations or visualizations should be added based on the Object Table?

Notes:
* This version is for Run 1.2i, but can be easily changed by specifying a different catalog.
* This version uses the Parquet file of the DPDD quantities, but could easily be changed to use the GCR catalog access model.

### CODE REVIEW

**Comment by yymao** [comment]
- Move to the `validation/` directory (see #42)? 


- If use `base_dir` is needed but not the actual catalog instance, you can do:
   ```python
   dpdd_parquet_dir = GCRCatalogs.get_catalog_config(catalog_name)['base_dir']
   ```
   to save time on initiation of the catalog instance.

**Comment by wmwv** [comment]
@fjaviersanchez Could you take a look at this PR when you have the chance?

**Comment by wmwv** [comment]
Ah, yes the `assets/Davenport_2014_MNRAS_440_3430_table1.txt` is missing because it needs to be where this Notebook will be moved to, and I was intending for this to go to `contributed`.  But, no, I didn't intend to submit a Notebook that doesn't work.  I've made the link now `../contributed/assets/Davenport_2014_MNRAS_440_3430_table1.txt` as this should work regardless of which subdirectory the Notebook ends up in.

On that note:
@yymao @fjaviersanchez Can you vote on whether this Notebook should go into the `tutorials` subdirectory or a new `validation` subdirectory?

**Comment by fjaviersanchez** [comment]
I just noticed that #42 (which adds a `validation` directory and a couple of notebooks) is approved but not merged. I think that it would be best if this notebook were in the `validation` directory. However, I don't know if the easiest thing to do right now would be to just approve and merge this (so we avoid merging conflicts). After that, we can move it if that's fine with everyone.

**Comment by wmwv** [comment]
The should be no merge conflicts on the simple creation of a directory.  I'm happy to rebase if necessary.

**Comment by wmwv** [comment]
@fjaviersanchez If you really want to make sure, you could just merge #42 and I'll make sure it's all good with that.

**Comment by fjaviersanchez** [comment]
Thanks! I just merged. Please go ahead and rebase and I'll go ahead and approve the PR.

**Comment by wmwv** [comment]
@fjaviersanchez Rebased, touched-up, and ready to be re-approved.

**Pull request merged**
