### PR TITLE
contributing blending analysis notebooks

### PR DESCRIPTION
**Pull request by BhairavValera**
Changed location of the notebooks I was contributing to for organizational purposes.

### CODE REVIEW

**Comment by yymao** [comment]
@BhairavValera can you clear the notebook output? On NERSC, you can run:
```bash
/usr/common/software/python/3.6-anaconda-4.4/bin/jupyter nbconvert --clear-output FoFPlotResults.ipynb
/usr/common/software/python/3.6-anaconda-4.4/bin/jupyter nbconvert --clear-output postage_stamps_brightobjects.ipynb
```

**Comment by BhairavValera** [comment]
@yymao I ran those two lines and recommitted my notebooks.

**Comment by yymao** [comment]
@BhairavValera thanks! Note that you haven't pushed your new changes yet (so it's not yet visible for me). While you are at this, it'll also be good to add the contributors' names on top of the notebooks so that people know who to contact if they have questions.

**Comment by rmandelb** [comment]
@BhairavValera - I just noticed this pull request was waiting.  It seems you pushed some commits addressing @yymao 's comments; are the notebooks ready for a more detailed review?

**Comment by BhairavValera** [comment]
@rmandelb - The notebooks have not gone under any major alterations in the past couple of months. I had changed them regarding @yymao 's concerns and have not made any significant other changes since. With regards to the review, the notebooks themselves work fine but I would like to thoroughly comment both of them so it becomes easier to interpret what they do. I can have these notebooks ready for a review by Sunday evening. Is that okay?

**Comment by yymao** [comment]
@BhairavValera the instruction I gave you above on clearing the output was not correct. When you are done with updating the notebooks, please run:
```bash
/usr/common/software/python/3.6-anaconda-4.4/bin/jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace *.ipynb
```
to clear the output. 

Also, leave the figures that are generated by the notebooks out of the commits. Thanks!

**Comment by BhairavValera** [comment]
@yymao I was running through my notebooks and noticed an issue with regards to the truth catalog. I am running with `dc2_truth_run1.1` and `dc2_coadd_run1.1p` and matching is no longer working when it

**Comment by BhairavValera** [comment]
@yymao I was running through my notebooks, adding comments for the review, and noticed an issue with regards to the truth catalog. I am running with dc2_truth_run1.1 and dc2_coadd_run1.1p and matching is no longer working due to the size of each catalog being different. Has the truth catalog been changed in some way or are we now using a different version of the catalog? 1.2?

**Comment by yymao** [comment]
@BhairavValera Can you provide more information: (1) Did the issue happen in `FoFPlotResults.ipynb`, and which cell? (2) What error message did you get? (3) What lengths are you referring to? Note that we don't expect these catalogs have the same length. 

Also, I notice some settings are not up-to-date. You can disable the following `sys.path.insert` statements because these packages should be installed in the shared environment.

```python
#sys.path.insert(0, '/global/common/software/lsst/common/miniconda/current/lib/python3.6/site-packages')
#sys.path.insert(0, '/global/homes/b/bhairav/gcr-catalogs')
```

Also, you may want to update your kernels since they have been updated recently. You can do that by logging into cori.nersc.gov and run:
```bash
/global/common/software/lsst/common/miniconda/kernels/setup.sh
```

**Comment by yymao** [comment]
@BhairavValera actually this may be related to a bug in GCR, which I just fixed (https://github.com/yymao/generic-catalog-reader/pull/24). It'll be updated to the shared environment later.

**Comment by yymao** [comment]
@BhairavValera 

For `FoFPlotResults.ipynb`, remember to remove the following lines:
```python
sys.path.insert(0, '/global/common/software/lsst/common/miniconda/current/lib/python3.6/site-packages')
sys.path.insert(0, '/global/homes/b/bhairav/gcr-catalogs')
```
The beginning of the notebook is also outdated, as both packages are now installed in `desc-python`. 


For `postage_stamp_generation.ipynb`, if you use the current `desc-stack` kernel, you will need to add the following (after #31 is merged):
```python
import sys
sys.path.insert(0, '../tutorials')
from utils.DMProduct import REPOS
```

And then you can just do:
```python
butler = dafPersist.Butler(REPOS['1.1p'])
```
and the notebook should work.

**Comment by BhairavValera** [comment]
@yymao 
I removed those lines and recommitted. You mentioned that "both packages are now installed in `desc-python`" and that the beginning of the `FoFResults.ipynb` is outdated. Were you referring to the two packages from the `sys.path.insert(...)` or something else.
With regards to the `postage_stamp_generation.ipynb`, there seems to be an issue with the `desc-stack` kernel. It can't initialize and I get the message `No Kernel!` so I can't run with the `desc_dc2_dm_data` module. Any suggestions?

**Comment by yymao** [comment]
@BhairavValera I was referring to the markdown note at the beginning of `FoFResults.ipynb`
> This notebook uses a current PR of gcr-catalogs, make sure you clone the PR and add it to sys.path
> git clone -b coadd_reader git@github.com:djperrefort/gcr-catalogs.git
> This notebook also requires FoFCatalogMatching: https://github.com/yymao/FoFCatalogMatching
This note is no longer necessary. 

Have you tried reinstall DESC kernels? Run `/global/common/software/lsst/common/miniconda/kernels/setup.sh` on cori.nersc.gov to see if that fixes the kernel.

**Comment by BhairavValera** [comment]
@yymao 
Okay that worked, thank you! I believe the notebooks are ready for a review. Please let me know if you need anything else!

**Comment by yymao** [comment]
@BhairavValera thanks for the update. I tried to run through the notebook but the FoF matching step never finishes (takes more than an hour). Is that expect?

**Comment by kakoon** [comment]
It usually took long time for me too. (more than an hour)

Best,
HyeYun Park

*Stony Brook University Physics and Astronomy*
*Brookhaven National Laboratory*
*Large Synoptic Survey telescope*
*Dark Energy Science Collaboration*
*Office: (631) 344-4060*
*Mobile: (631) 605-0038*

**Comment by BhairavValera** [comment]
@yymao it should not take _too_ long to run. If you are running with a linking length of 1 arcsec (or less), it should only take about 20 minutes to run. Any higher linking lengths (like 2 or 3 arcsec) will take much longer (~hours). I'm not so sure what the problem could be. On my machine, it seems to run fine.

**Comment by yymao** [comment]
@BhairavValera hmm, even with 1 arcsec linking length it still won't finish within an hour. When you said it runs fine on your machine, do you mean on a non-nersc machine?

**Comment by BhairavValera** [comment]
@yymao When I said on my machine, I meant my laptop connected to a nersc server through Jupyter. Apologies for not being specific! I tried running again today and seems I am running into the same problem as you are. The cell does not seem to finish even after 2 hours of running. I believe this might have something to do with the recent kernel updates. Before updating it would definitely finish faster. Is it possible to revert to a previous version of the desc-stack/desc-python kernel?

**Comment by yymao** [comment]
I am surprised that the update to `desc-python` slows this down, because updates to `desc-python` are usually just just new/updated packages that are (IMO) unlikely to affect the performance of the FoF code. 

cc @heather999 to see if she keeps an older version of `desc-python`.

**Comment by heather999** [comment]
I do keep older versions. In this case, we have the `desc-python-old` kernel which will point to the older version of python associated with older versions of the DMstack.  The downside is that this may or may not include updated versions of gcr-catalogs or the newer desc_dc2_dm_data.  I've basically stopped updating the older python installation.  We can try it and see what happens though.

**Comment by BhairavValera** [comment]
Happy new year, everyone! Sorry I have not been very communicative lately, things got very hectic at school.
In terms of running using the older kernel versions, the `FoFResults.ipynb` still takes too long to run. I'm not sure what the problem could be because the only changes I made to the notebook since early November were adding the comments. Any other suggestions for fixing this issue? It is primarily cell 8 that is taking a long time to run:
`results = FoFCatalogMatching.match(
    catalog_dict=dict(ref=coordinatesRefCat, coadd=coordinatesCoaddCat),
    linking_lengths=1.0,
    catalog_len_getter=lambda x: len(x['ra']))`
Were there any significant changes made to the `FoFCatalogMatching` module in a recent update? Thanks!

**Comment by rmandelb** [comment]
@BhairavValera - sorry for the very slow response; I had some crossed wires about finding reviewers. @mclaughlin6464 has kindly agreed to go over this.

**Comment by mclaughlin6464** [comment]
I've installed the packages and was able to get both notebooks to run. The code is a little dense, but I don't think there's anything to be done about that. I was able to follow well enough. 

My only complaint/suggestion is that the FoF matching notebook needs to be run before the postage stamps one. There isn't an obvious sequence to them, so I'm not sure why this is the case. Would it be possible to save the data as numpy arrays in the directory, so the postage stamp notebook could be run independently? I wasnt sure if the files were too large.

**Comment by BhairavValera** [comment]
@mclaughlin6464 
Hi, Sean, sorry for the slow response. Things were kind of hectic at school.
With regards to your question, running the `FoFResults.ipynb` notebook basically generates the data we then use in `postage_stamp_generation.ipynb`. As far as I am aware, you would only need to run `FoFResults.ipynb` once because it will always group objects together the same way (provided you are not changing the linking length). Once you have the results from `FoFCatalogMatching.match`, you won't need to run the whole notebook again.
It is certainly possible to save all of the data to numpy arrays in a separate file using `numpy.save` (https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html) but I have been having some difficulty getting into Jupyter lately, so I haven't been able to try this yet. I'm not sure if the file sizes (we could probably save the data as .txt) would be too big. I will try this as soon as I figure out what is going on with NERSC/Jupyter access. Feel free to try this yourself!
Also, Jupyter has its own way of storing data: you can type `%store insert_name_of_data_structure here` to locally save it within Jupyter itself and then in another notebook, type `%store -r insert_name_of_data_structure here` to read it. I do think the numpy way is better though; thanks for pointing that out. I will get to changing that soon. Let me know if you have any other concerns!

**Comment by reneehlozek** [comment]
hi @BhairavValera, I wanted to check if you were planning on making more changes to this notebook related to @mclaughlin6464 comments?

**Comment by slosar** [comment]
@BhairavValera lost access to NERSC, let me see if something can be done about that.

**Comment by reneehlozek** [comment]
I'm going to suggest that we close this, since it isn't clear the changes can be made?

**Comment by slosar** [comment]
yes

**Pull request closed without merging**
