### PR TITLE
add spark tutorial entry in the readme file

### PR DESCRIPTION
**Pull request by yymao**
This PR adds the recently merged Spark tutorial as an entry in the tutorial readme file so that it's easy to see its build status.

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Out of curiosity: where do you set the correct kernel associated to a notebook for the rendering?

**Comment by yymao** [comment]
Thanks, @JulienPeloton.

We use [`beavis-ci`](https://github.com/LSSTDESC/beavis-ci) to render the notebooks, and it uses the kernel that matches the kernel specified in each of the notebooks. The available kernels are those of the user who runs the beavis-ci job (in this case, me), and my kernels come from the DESC kernel setup script (i.e., from https://github.com/LSSTDESC/jupyter-kernels).

**Comment by JulienPeloton** [comment]
Thanks @yymao for the explanations!

**Comment by JulienPeloton** [comment]
But then it will fail for beavis-ci as you won't have the permissions to create folders for tmp & log files (from the startup script).  Should I add conditions on the environment when paths are set up?

**Comment by yymao** [comment]
Yes, @JulienPeloton, see my PR at https://github.com/LSSTDESC/jupyter-kernels/pull/2

**Pull request merged**
