### PR TITLE
U/wmwv/holoviews

### PR DESCRIPTION
**Pull request by wmwv**
* Demonstrates using a Dask Cluster on a NERSC interactive job node as a backend to feed a JupyterHub HoloViews+DataShader visualization of basic quantities in DC2 Run 2.2i DR6a.
* Please check that the instructions work for you.  It's a few steps to set up the Dask Cluster with the right Python environment.
* Future work will adapt the full DC2 Run 2.2i object validation Notebook to dask.
But I'd like to get this simple demonstration of how to do this out there.

### CODE REVIEW

**Comment by wmwv** [comment]
Thanks, @SimonKrughoff !  I addressed the various points above and respond to a few here:

> I think it would be good in the instructions to help users not tread on each other. Changing the instructions to use ${SCRATCH}/${USER} instead of just $SCRATCH would help with that.

${SCRATCH} on NERSC is per user.  E.g., for me it's `/global/cscratch1/sd/wmwv`.  I've added a note explaining that.

> Zooming in on the interactive plots doesn't seem to cause the adaptive refinement I expect from datashader. The text makes it seem the interactive rebinning is expected to work.
Yes!  I thought this was supposed to work too, I can't figure out why it doesn't.  I'll fix the text for now but hopefully will figure this out in the near future.

> Cell 15 doesn't seem to be used anywhere, so should probably be removed for clarity.
Thanks.  I wasn't actually using `points_mag_magerr` until the hover-over example at the end.  

I've restructured the plots to show just the Ra, Dec one first and then the triplet.  I originally was putting the RA, Dec plot with the color_mag and color_color plots because I was trying to get brushing+linking working across all three plots.  I'll try to tackle that in a future improvement, likely when I figure out the re-rastering thing as well.

> To invert the y-axis, this seems to work ra_dec + color_mag.opts(invert_yaxis=True) + color_color
Oh, thank you.  This works for this first set of plots, but doesn't work for the mag vs. mag_err and mag vs. color plot below because it inverts both of the mag axes, even if I just apply to one (because the selections are linked).

> I would clear all outputs before merging since the notebook outputs don't contain much information without the plots and the numbers make it hard to tell which cells have been run and which haven't.
Certainly.  I will commit a rendered version to the `rendered` branch, and then clear and perhaps rewrite history for this branch before merging.

**Comment by wmwv** [comment]
> I find the dask dashboard really helpful, but it doesn't seem to be working at nersc.
@cwwalter Can you check to see if this works for you, when you+NERSC are both powered-up at the same time?

**Comment by cwwalter** [comment]
Hi @wmwv ,  PR is merged so I will do this as a comment:

Very nice notebook / intro! OK here are some small pedagogically geared comments + a few Pandas style suggestions.

- To meet your learning goals: Maybe a few sentences on what parquet is and why it is a good choice for us would be nice.

- In the read-in command:

```
df = dd.read_parquet(datafile, columns=columns_to_read, engine='pyarrow')
```

You have just given it a directory, with no globs etc for the datafile name.  So it  it knows it should then read the whole directory.  It might be nice to note this and also say what to do if I wanted to include (say) 5 specific files.  In fact I think it might be better to use a different variable name here since really you are giving it a "path-like" instead of a "file-like" object.  (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_parquet.html)

- This part could go somewhere else, but a few lines about why one would want to use Dask might be nice.  In particular, it might be interesting to think here about where you could switch back to standard pandas and mention that if the memory gets small enough you might want to do that. In this particular case, we can see for dr6a when you selected a sub-set you are now probably down to a size one could deal with without the Dask overhead:

image

- You are using the original pandas selection technique which I find too repetitive and wordy if I am dealing with variables in the same data frame.  So, as a simple example, doing this:

```
gal = df[(df.extendedness > 0.95)]
```

In most case I usually do this instead (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html?highlight=query#pandas.DataFrame.query):

```
gal = df.query('extendedness > 0.95')
star = df.query('extendedness < 0.95')
```

I think that is much easier to read and it is more compact/ easier to copy/edit etc.  But, note that when I tried to convert 

```
df = df[(df.magerr_g < snr_magerr_threshold) & (df.magerr_r < snr_magerr_threshold) & (df.magerr_i < snr_magerr_threshold)]
```
Dask complained.  It apparently is confused since it needs to, and doesn't know the type of snr_magerr_threshold to carry around.   You can apparently tell it by adding something like  meta=('snr_magerr_threshold', float) to the command but I didn't quite get it to work (but didn't try hard).  I just did this to check it gave the same results:

```
df = df.query('magerr_g < 0.3 & magerr_r < 0.3 & magerr_i < 0.3')
```

- The holoview/datashader stuff is quite cool.  I don't know enough about it to really give any useful feedback.  But, I can tell you one thing I found confusing:  In dask I am used to after all the lazy stuff happens to have to do a compute() of some sort.  But, I see that nowhere here.  I assume this is because holoviews is dask-aware and is doing it for me somehow?  It might be nice to note this.

**Comment by wmwv** [comment]
Thanks, @cwwalter !  I will add these comments to this Notebook in a later PR.

I'll also think about some of these notes for the larger DC2 Run2.2i DR6 Notebook I'm working on now and plan to have ready for review once Cori is back up next Wednesday.

**Comment by cwwalter** [comment]
I knew there was something I forgot! I remembered it as soon as I hit enter 😬.

-  I was a bit confused by this language: "For simple testing and illustration of how to use dask, holoview, and datashader here you can run locally on just one tract. To run on the full set of DR6, you'll need to set up a node to support Dask distributed. Basically you just need a machine that can hold the data in memory."

I'm not sure what the part about holding the data in memory means since one of the reasons we are using dask to to get out of core operations. Does the last sentence refer to just the first part about one tract?

Then I wanted to note outside of the comments above:

I wasn't really setup to try this at NERSC on short notice. Also, I knew NERSC was shutting down this morning.

So, I copied the dr6a files to my laptop with globus last night. Then, I  made a new conda env installing  dask, pandas, holoviews, datashader, and pyarrow. I skipped all the dask setup cells and it just worked 1st time! 🎉 .  So that is great.  It really shows how portable the setup is. 

By default it just uses the the default dask scheduler and there is no setup at all.  So, I didn't look at what it was doing.   But from looking at my CPU menu thing it looks like it was using all of the cores.  I may try to setup something explicit later and even use a few laptops in a cluster to see what it does.  But the point is that if this works at NERSC it also worked in my house by doing nothing except skipping some cells.

**Comment by cwwalter** [comment]
I also should note that I have a 32Gb machine and it processed and made the  plots on the 42Gb of parquet files with no problems.

**Comment by wmwv** [comment]
> I'm not sure what the part about holding the data in memory means since one of the reasons we are using dask to to get out of core operations. Does the last sentence refer to just the first part about one tract?

1. Loading more data than fit into memory.  You can delay this in either time or space (spin up additional machines).
2. Distributing work across multiple processors.  Python and numpy/scipy are not naturally parallel or easily parallelizable.  One of the common things we will do with large datasets is aggregate for both analysis and visualization.  Being able to do this aggregation in parallel is a significant gain.

#2 is a key part of the difference between saying:

**Comment by wmwv** [comment]
#2 is a key part of the difference between saying:

```
df_pandas = df.compute()
```

vs

```
df_dask = df.persist()
```

`df_pandas` may work if it all fits into memory, but aggregation will be done largely serially.  If you only have 4 real cores anyway, the difference is small.  But if you're running with an entire NERSC node as a backend (32 real cores), then difference is significant and noticeable.

**Comment by cwwalter** [comment]
Right. I understand.

That's why I think the sentence: ""For simple testing and illustration of how to use dask, holoview, and datashader here you can run locally on just one tract. To run on the full set of DR6, you'll need to set up a node to support Dask distributed. Basically you just need a machine that can hold the data in memory." is confusing (to me anyway). 

 It seems to be saying the opposite of this.

**Comment by wmwv** [comment]
Totally agree.  I will re-write.

**Pull request merged**
