### PR TITLE
U/wmwv/calexp postage stamp from coadd

### PR DESCRIPTION
**Pull request by wmwv**
Demonstrate how to load postage stamps and forced-photometry from the individual visit-level data for objects identified from the Object table based on the coadded images.

@ehneilsen @rmjarvis I wrote this following your questions at the DESC meeting.
* Is this what you were looking for?
* What could be clearer?
* Is there anything additional?

@EiffL I believe this is relevant for your metacal work as well if you want to go through individual images.  I'd be interested in your feedback as well along with any simplifications or alternate approaches you might recommend.

There are two outstanding issues, but I'd like to get your feedback about the overall direction and utility of the notebook before polishing those up.

Outstanding Issues:
* [ ] One unfortunate bit is that for Run 1.1 there were just a few images for each coadd so I haven't found an object that results in multiple visits for the forced photometry.  If you find such an object, please let me know and I'll use that one instead.  It's also possible that I'm doing something subtly wrong and thus not finding the objects.
* [ ] I should experiment with using the calexp WCS to look up whether or not a location falls within the image rather than matching the object ID in the forced source catalog.  This naively should make `get_all_images_for_object_id_from_data_ids` faster.

### CODE REVIEW

**Comment by wmwv** [comment]
@yymao Here's some code to do RA, Dec -> tract, patch -> overlapping visits.

As noted in the PR text, I should work to make it faster, but here's the idea in case you're interested in taking a look for your postage-stamp server work.

**Comment by yymao** [comment]
@wmwv Thanks for the pointers! Turns out it's not as straightforward as I thought to write a clean cutout service API that works seamlessly for both coadd images and per-visit images. [Here's what I have right now](https://github.com/LSSTDESC/cutout-service/blob/master/cutout_maker.py#L21) that only works for coadd images. I'll need to give it some more thoughts. In the meantime, your input is certainly very welcome, or we can discuss more in person when you are back to Pittsburgh.

**Comment by reneehlozek** [comment]
hi @wmwv, just wanted to check the status of this PR, were the data access issues solved?

**Comment by reneehlozek** [comment]
hi @EiffL, @rmjarvis, @ehneilsen - are there additional things you need from @wmwv in this PR?

**Comment by rmjarvis** [comment]
Not me.  (I mostly use full calexps, not postage stamps, so tbh, I didn't look to closely at the details of this.)

**Pull request merged**
